### ISSUE TITLE
"You did not deploy any project to BeamUp"

### ISSUE THREAD

**Issue by Vance-ng-vn** [Stremio/beamup-panel#1]
I tried running it, it returns my github doesn't have any projects yet!

Is this project linked to a.baby-beamup.club?

Before that, I used beamup-cli, that used an ssh key instead of oauth

**Comment by jaruba** [comment]
This is not meant to run locally or to be deployed to any beamup host by users.

Stremio created the BeamUp project (the code for it), which can be hosted on a server. The panel is still in development and is meant to be deployed to BeamUp servers.

While BeamUp has no database of user information, it uses part of a hash from the github username of the person that is deploying for the addon subdomain name. Based on that hash the panel can recognize the user's deployments, and thus give access to actions for those deployments. (such as: see logs, restart, delete)

As I said though, this project is still in development.

**Comment by Vance-ng-vn** [comment]
Amazing, it's already available on Baby-Beamup.
